### PR TITLE
update readme and ci scripts to use new pull methods

### PR DESCRIPTION
**Pull request by jeking3**
The ci files are now pulled from https://www.github.com/jeking3/boost-ci during the build process.  This allows them to be updated "en masse".

This PR updates the readme badges and I have enabled both Appveyor and Travis CI build jobs, so they should kick in normally on the PR.

### CODE REVIEW

**Comment by jeking3** [comment]
Yep, so, merging was a bad thing.  The builds failed.  In the future, let's wait for the builds to pass.

**Comment by jeking3** [comment]
Good news - all the builds are working again:

Appveyor: https://ci.appveyor.com/project/jeking3/signals2-db91c/build/1.0.7-develop
Travis: https://travis-ci.org/boostorg/signals2/builds/387260353

**Comment by fmhess** [comment]
So should it be merged to master now?

**Comment by jeking3** [comment]
It is stable and passes all builds successfully.  I've added a once-monthly develop branch cron job as well to get a Coverity Scan analysis (it is supposed to happen on any push to develop, but a squash or rebase in the GitHub UI may not trigger it - not sure yet).

**Comment by jeking3** [comment]
I'm working with Travis support to figure out why the Coverity Scan job isn't running, if an additional change is needed (like in `.travis.yml`) there I will submit another PR.

**Pull request merged**
